BloodBank/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name="bloodbank"

urlpatterns=[
    path('register/',views.UserCreate.as_view(),name="register"),
    path('',views.Index.as_view(),name="index"),

    #Donor Url
    path('view_donor',views.ViewDonor.as_view(),name="view_donor"),
    path('add_donor',views.AddDonor.as_view(),name='add_donor'),
    path('<int:pk>/delete_donor',views.DeleteDonor.as_view(),name='delete_donor'),
    path('<int:pk>/edit_donor',views.EditDonor.as_view(),name='edit_donor'),

    #Reciever Url
    path('view_receiver',views.ViewReceiver.as_view(),name="view_receiver"),
    path('add_receiver',views.AddReceiver.as_view(),name='add_receiver'),
    path('<int:pk>/delete_receiver',views.DeleteReceiver.as_view(),name='delete_receiver'),
    path('<int:pk>/edit_receiver',views.EditReceiver.as_view(),name='edit_receiver'),
    
    #Inventory Url
    path('view_inventory',views.ViewInventory.as_view(),name="view_inventory"),
    path('add_reviever',views.AddInventory.as_view(),name='add_inventory'),
    path('<int:pk>/delete_inventory',views.DeleteInventory.as_view(),name='delete_inventory'),
    path('<int:pk>/edit_inventory',views.EditInventory.as_view(),name='edit_inventory'),

]

HealthCare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myuser.urls')),
    path('ambulance/',include('Ambulance.urls')),
    path('bloodbank/',include('BloodBank.urls')),
    path('hospital/',include('Hospital.urls')),
    path('mdstore/',include('Medical_Store.urls')),
]

myuser/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name="myuser"

urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('search_ambulance', views.SearchAmbulance.as_view(),name='search_ambulance'),
    path('<int:pincode>/view_ambulance', views.ViewAmbulance.as_view(),name='view_ambulance'),
    path('search_hospital', views.SearchHospital.as_view(),name='search_hospital'),
    path('<int:pincode>/view_hospital', views.ViewHospital.as_view(),name='view_hospital'),
    path('search_bloodbank', views.ViewBloodbank.as_view(),name='search_bloodbank'),
    path('<int:pincode>/view_bloodbank', views.ViewBloodbank.as_view(),name='view_bloodbank'),
    path('search_medicine', views.SearchMedicine.as_view(),name='search_medicine'),
    path('<int:pincode>/view_medicine', views.ViewMedicine.as_view(),name='view_medicine'),
    path('register/',views.UserFormView.as_view(),name='register'),
    path('<pk>/delete',views.Delete.as_view(),name='delete'),
    path('logout/',views.LogoutView.as_view(),name='logout')
    # path('forgotpassword/',views.forgotpassword,name='forgotpasssword')
]

BloodBank/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from myuser.models import Myuser,City
import datetime

BLOOD_GROUP=[
    ('A+','A+'),
    ('B+','B+'),
    ('O+','O+'),
    ('AB+','AB+'),
    ('A-','A-'),
    ('B-','B-'),
    ('O-','O-'),
    ('AB-','AB-'),
]

#BB-Details
class BB_Details(models.Model):
        
    name=models.CharField(max_length=100)
    address=models.CharField(max_length=500)
    city=models.ForeignKey(City,on_delete=models.DO_NOTHING)
    pincode=models.PositiveIntegerField(validators=[MaxValueValidator(999999),MinValueValidator(100000)])
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

#Blood INventory
class Blood_Inventory(models.Model):
    blood_group=models.CharField(max_length=3,choices=BLOOD_GROUP)
    no_of_units=models.IntegerField(default=0)
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)

#Donor Details
class Donor(models.Model):
    name=models.CharField(max_length=100)
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    email=models.EmailField(max_length=256)
    area=models.CharField(max_length=200)
    blood_group=models.CharField(max_length=3,choices=BLOOD_GROUP)
    date=models.DateField( default=datetime.date.today)
    no_of_units_donated=models.IntegerField(default=1)
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)


#Reciever Model
class Reciever(models.Model):
    name=models.CharField(max_length=100)
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    email=models.EmailField(max_length=256)
    blood_group=models.CharField(max_length=3,choices=BLOOD_GROUP)
    date=models.DateField(default=datetime.date.today)
    no_of_units_recieved=models.IntegerField(default=1)
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)

# Create your models here.

BloodBank/forms.py
from django import forms
from .models import Donor,Reciever,BB_Details,Blood_Inventory


class BBDetails(forms.ModelForm):
    class Meta:
        model= BB_Details
        fields=['name','address','city','pincode','contact','user']
        exclude=('user',)

class DonorDetails(forms.ModelForm):
    class Meta:
        model=Donor
        fields=['name','contact','email','area','blood_group','date','no_of_units_donated','user']
        exclude=('user',)

class RecieverDetails(forms.ModelForm):
    class Meta:
        model=Reciever
        fields=['name','contact','email','blood_group','date','no_of_units_recieved','user']
        exclude=('user',)

class BloodInventory(forms.ModelForm):
    class Meta:
        model=Blood_Inventory
        fields=['blood_group','no_of_units','user']
        exclude=('user',)

BloodBank/views.py
from django.views.generic import *
from django.views.generic.edit import *
from .models import *
from django.urls import reverse_lazy,reverse
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login,logout
from .forms import *
from django.http import HttpResponse

from django.contrib.auth.mixins import LoginRequiredMixin

BLOOD_GROUP=[
    ('A+','A+'),
    ('B+','B+'),
    ('O+','O+'),
    ('AB+','AB+'),
    ('A-','A-'),
    ('B-','B-'),
    ('O-','O-'),
    ('AB-','AB-'),
]

#Index Page
class Index(View):
    template_name='BloodBank/layout.html'

    def get(self,request):
        return render(request,self.template_name)


#Registration 
class UserCreate(LoginRequiredMixin,View):
    form_class=BBDetails
    template_name='BloodBank/register.html'
        
    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return redirect('bloodbank:index')
        
        return render(request,self.template_name,{'form':form})
    
    
#Donor Details
#Add_Details
class AddDonor(LoginRequiredMixin,View):
    form_class=DonorDetails
    template_name='BloodBank/donor_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            print(provider.blood_group)
            blood=get_object_or_404(Blood_Inventory,blood_group=provider.blood_group)
            blood.no_of_units=blood.no_of_units+provider.no_of_units_donated
            blood.save()
            return redirect('bloodbank:view_inventory')
        
        return render(request,self.template_name,{'form':form})


#list Donor
class ViewDonor(ListView):
    template_name='BloodBank/donor.html'
    context_object_name='donors'
    model=Donor
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)

#edit donor
class EditDonor(UpdateView):
    model=Donor
    form_class=DonorDetails
    template_name='BloodBank/donor_form.html'
    success_url=reverse_lazy('bloodbank:view_donor')

#Delete donor
class DeleteDonor(DeleteView):
    model=Donor
    success_url=reverse_lazy('bloodbank:view_donor')


#Reciever Views
class AddReceiver(LoginRequiredMixin,View):
    form_class=RecieverDetails
    template_name='BloodBank/receiver_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            blood_group=form.instance.blood_group
            required=form.instance.no_of_units_recieved
            blood=get_object_or_404(Blood_Inventory,blood_group=blood_group)
            if(blood.no_of_units>=required):
                print("1")
                blood.no_of_units=blood.no_of_units-required
                blood.save()
                provider=form.save(commit=False)
                form.instance.user = self.request.user
                provider.save()
                return redirect('bloodbank:view_inventory')
            else:
                return render(request,self.template_name,{'form':form})
        return render(request,self.template_name,{'form':form})

#list Reciever
class ViewReceiver(ListView):
    template_name='BloodBank/receiver.html'
    context_object_name='receivers'
    model=Reciever
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)

#edit reciever
class EditReceiver(UpdateView):
    model=Reciever
    form_class=RecieverDetails
    template_name='BloodBank/receiver_form.html'
    success_url=reverse_lazy('bloodbank:view_receiver')

#Delete reciever
class DeleteReceiver(DeleteView):
    model=Reciever
    success_url=reverse_lazy('bloodbank:view_receiver')


# Inventory views
#Add Inventory
class AddInventory(LoginRequiredMixin,View):
    form_class=BloodInventory
    template_name='BloodBank/inventory_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return redirect('bloodbank:view_inventory')
        return render(request,self.template_name,{'form':form})

    

#list Reciever
class ViewInventory(ListView):
    template_name='BloodBank/inventory.html'
    context_object_name='inventory'
    model=Blood_Inventory
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)

#edit reciever
class EditInventory(UpdateView):
    model=Blood_Inventory
    form_class=BloodInventory
    template_name='BloodBank/inventory_form.html'
    success_url=reverse_lazy('bloodbank:view_inventory')

#Delete reciever
class DeleteInventory(DeleteView):
    model=Blood_Inventory
    success_url=reverse_lazy('bloodbank:view_inventory')




# Create your views here.

templates/BloodBank/add_donor.html
{% extends 'BloodBank/layout.html'%}
{% block title %} Donor Registration {% endblock %}
{% block body %}
    <div class="heading">
      		<h2>Donor Details</h2>
      	</div>
      	<div class="custom-form">
                <form method="POST" action="">
				{% csrf_token%}
                	<label for="name">Name</label><br>
                    {% comment %} <input type="text" name="name" id="name" placeholder="name"><br> {% endcomment %}
					{{ form.name }}<br>
                    <label for="contact">Contact No</label><br>
					{{ form.contact }}<br>
                    {% comment %} <input type="text" name="contact" id="contact" placeholder="contact"><br> {% endcomment %}
                    <label for="email">Email</label><br>
					{{form.email}}<br>
                    {% comment %} <input type="text" name="email" id="email" placeholder="email"><br> {% endcomment %}
                    <label for="area">Area</label><br>
					{{ form.area }}<br>
                    {% comment %} <input type="text" name="area" id="area" placeholder="area"><br> {% endcomment %}
                    <label for="blood_group">Blood Group</label><br>
                    {{ form.blood_group }}<br>
                    <label for="no_of_units_donated">No of units donated</label><br>
					{{ form.no_of_units_donated }}<br>

					<input type="submit" name="Submit" id ="Submit" value="Submit">
                </form>
            </div>
{% endblock %}

templates/BloodBank/add_inventory.html
{% extends 'BloodBank/layout.html'%}
{% block title %} Inventory {% endblock %}
{% block body %}
    <div class="heading">
      		<h2>Inventory Details</h2>
      	</div>
      	<div class="custom-form">
                <form method="POST" action="">
                {% csrf_token%}
                    <label for="blood_group">Blood Group</label><br>
                    {{ form.blood_group }}<br>
                    <label for="no_of_units">No of units</label><br>
					{{ form.no_of_units }}<br>

					<input type="submit" name="Submit" id ="Submit" value="Submit">
                </form>
            </div>
{% endblock %}

templates/BloodBank/add_receiver.html
{% extends 'BloodBank/layout.html'%}
{% block title %} Receiver Registration {% endblock %}
{% block body %}
    <div class="heading">
      		<h2>Receiver Details</h2>
      	</div>
      	<div class="custom-form">
                <form method="POST" action="">
				{% csrf_token%}
                	<label for="name">Name</label><br>
                    {% comment %} <input type="text" name="name" id="name" placeholder="name"><br> {% endcomment %}
					{{ form.name }}<br>
                    <label for="contact">Contact No</label><br>
					{{ form.contact }}<br>
                    {% comment %} <input type="text" name="contact" id="contact" placeholder="contact"><br> {% endcomment %}
                    <label for="email">Email</label><br>
					{{form.email}}<br>
                    {% comment %} <input type="text" name="email" id="email" placeholder="email"><br> {% endcomment %}
                    <label for="blood_group">Blood Group</label><br>
                    {{ form.blood_group }}<br>
                    <label for="date">Date</label><br>
                    {{ form.date }}<br>
                    <label for="no_of_units_recieved">No of units received</label><br>
					{{ form.no_of_units_recieved }}<br>

					<input type="submit" name="Submit" id ="Submit" value="Submit">
                </form>
            </div>
{% endblock %}

templates/BloodBank/base.html
<!DOCTYPE html>
<html>
    
<head>
	<title>{% block title %}{% endblock %}</title>
  {% load static  %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'myuser/css/register.css' %}"/>
  
</head>
<body>
	</head>
<body>
    <header>

        <a id="logo" href="#">
            <img src="{% static 'myuser/css/logo.png' %}" alt="Logo">
            <span>Frontida</span>
        </a>

        <nav>
            <ul>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </nav>

    </header>
    {{% block body %}
{% endblock %}}
</body>
</html>

templates/BloodBank/donor.html
{% extends 'BloodBank/layout.html'%}
{% load static %}
{% block title %}Donor{% endblock %}
{% block body %}
     <h3>Donor</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <br><br><br>

                    <a href="{% url 'bloodbank:add_donor'%}">
                        <button type="button" class="btn btn-dark btn-group-small" height="45px">
                            Add 
                        </button>
                    </a>

                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Blood group</th>
                            <th>Units donated</th>
                            <th>Contact</th>
                            <th>Email</th>
                            <th>Area</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for donor in donors %}
                            <tr>
                                <td>
                                    {{ donor.name }}
                                </td>
                                <td>
                                    {{ donor.blood_group}}
                                </td>
                                <td>
                                    {{donor.no_of_units_donated}}
                                </td>
                                <td>
                                    {{donor.contact}}
                                </td> 
                                <td>
                                    {{donor.email}}
                                </td>
                                <td>
                                    {{donor.area}}
                                </td>
                                
                                <td>
                                    <form action="{% url 'bloodbank:delete_donor' donor.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-trash"></i>
                                     </button>
                                     </form>
                                 </td>
                                 <td>
                                     <form action="{% url 'bloodbank:edit_donor' donor.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-edit"></i>
                                     </button>
                                     </form>
                                 </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

{% endblock %}

templates/BloodBank/donor_form.html
{% extends 'BloodBank/layout.html'%}
{% block title %} Donor Registration {% endblock %}
{% block body %}
    <div class="heading">
      		<h2>Donor Details</h2>
      	</div>
      	<div class="custom-form">
                <form method="POST" action="">
				{% csrf_token%}
                	<label for="name">Name</label><br>
                    {% comment %} <input type="text" name="name" id="name" placeholder="name"><br> {% endcomment %}
					{{ form.name }}<br>
                    <label for="contact">Contact No</label><br>
					{{ form.contact }}<br>
                    {% comment %} <input type="text" name="contact" id="contact" placeholder="contact"><br> {% endcomment %}
                    <label for="email">Email</label><br>
					{{form.email}}<br>
                    {% comment %} <input type="text" name="email" id="email" placeholder="email"><br> {% endcomment %}
                    <label for="area">Area</label><br>
					{{ form.area }}<br>
                    {% comment %} <input type="text" name="area" id="area" placeholder="area"><br> {% endcomment %}
                    <label for="blood_group">Blood Group</label><br>
                    {{ form.blood_group }}<br>
                    <label for="date">Date</label><br>
                    {{ form.date }}<br>
                    <label for="no_of_units_donated">No of units donated</label><br>
					{{ form.no_of_units_donated }}<br>
					<input type="submit" name="Submit" id ="Submit" value="Submit">
                </form>
            </div>
{% endblock %}

templates/BloodBank/inventory.html
{% extends 'BloodBank/layout.html'%}
{% load static %}
{% block title %}Blood Inventory{% endblock %}
{% block body %}
     <h3>Blood Inventory</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <br><br><br>

                    <a href="{% url 'bloodbank:add_inventory'%}">
                        <button type="button" class="btn btn-dark btn-group-small" height="45px">
                            Add 
                        </button>
                    </a>

                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th>Blood group</th>
                            <th>Units available</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for blood in inventory %}
                            <tr>
                                <td>
                                    {{ blood.blood_group }}
                                </td>
                                <td>
                                    {{blood.no_of_units}}
                                </td>
                               
                                <td>
                                    <!--ek baar next line check karna ki blood_inventory.id likhna hai ya only inventory.id-->
                                    <form action="{% url 'bloodbank:delete_inventory' blood.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-trash"></i>
                                     </button>
                                     </form>
                                 </td>
                                 <td>
                                     <form action="{% url 'bloodbank:edit_inventory' blood.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-edit"></i>
                                     </button>
                                     </form>
                                 </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

{% endblock %}

templates/BloodBank/inventory_form.html
{% extends 'BloodBank/layout.html'%}
{% block title %} Inventory {% endblock %}
{% block body %}
    <div class="heading">
      		<h2>Inventory Details</h2>
      	</div>
      	<div class="custom-form">
                <form method="POST" action="">
                {% csrf_token%}
                    <label for="blood_group">Blood Group</label><br>
                    {{ form.blood_group }}<br>
                    <label for="no_of_units">No of units</label><br>
					{{ form.no_of_units }}<br>

					<input type="submit" name="Submit" id ="Submit" value="Submit">
                </form>
            </div>
{% endblock %}

templates/BloodBank/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"></head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Hospital/css/layout.css' %}"/>
<title>{% block title%} {% endblock %}</title>

</head>
<body>
	<div id="container">
    <div id="header">
        <header>
        <a href="{% url 'bloodbank:index' %}">
            <img src="{% static 'myuser/css/logo.png' %}" alt="Logo" width="85">
        </a>
	 	<nav>
            <ul>
            	<li><a href="#">Home</a></li>
            	<li><a href="{% url 'myuser:logout' %}">LogOut</a></li>
                <div id="menuToggle">
    				<input type="checkbox" />
				    <span style="margin-top:-15px"></span>
				    <span></span>
				    <span></span>
				    <ul id="menu">
				      <a href="#"><li>Medical Store</li></a><br>
				      <a href="#"><li>Hospital</li></a><br>
				      <a href="#"><li>Patient Record</li></a><br>
				      
				    </ul>
  				</div>
            </ul>
        </nav>
    </header>
    </div>
    <div id="content">
      <div id="columns-container">
      <div class="column column-a">
      		<div class="Services">
	        <article>
	            <h2>Hi XYZ bloodbank</h2>!</h2>
	            <div class="custom-form" style="margin-left:0px">
					<div id="cover">
					  <form method="get" action="">
					    <div class="tb">
					      <div class="td"><input type="text" placeholder="Search"></div>
					      <div class="td" id="s-cover">
					        <button type="submit">
					          <div id="s-circle"></div>
					          <span></span>
					        </button>
					      </div>
					    </div>
					  </form>
					</div>
	            </div>
	        </article>
	        	<div class="Cards">
	            <ul>
	                <li>
	                    <img src="{% static 'Bloodbank/donor.jpg' %}" alt="donor"><br><br><br>
	                    <a href="{% url 'bloodbank:view_donor'%}">Donor</a>
	                </li>
					
	                <li>
	                    <img src="{% static 'Bloodbank/reciever.jpg' %}" alt="reciever"><br><br><br>
	                    <a href="{% url 'bloodbank:view_receiver'%}">Receiver</a>
                    </li>
					<br>
                    <li>
	                    <img src="{% static 'Bloodbank/inventory.jpg' %}" alt="inventory"><br><br><br>
	                    <a href="{% url 'bloodbank:view_inventory'%}">Inventory</a>
	                </li>
	            </ul>
	        	</div>
	    	</div>
      </div>
      <div class="column column-b">
	  {% block body %}
	  {% endblock %}
      </div>
      </div>
    </div>
</div>
</body>
</html>

templates/BloodBank/receiver.html
{% extends 'BloodBank/layout.html'%}
{% load static %}
{% block title %}Receivers{% endblock %}
{% block body %}
     <h3>Receiver Details</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <br><br><br>

                    <a href="{% url 'bloodbank:add_receiver'%}">
                        <button type="button" class="btn btn-dark btn-group-small" height="45px">
                            Add 
                        </button>
                    </a>

                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Blood group</th>
                            <th>Units received</th>
                            <th>Date</th>
                            <th>Contact</th>
                            <th>Email</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for receiver in receivers %}
                            <tr>
                                <td>
                                    {{ receiver.name }}
                                </td>
                                <td>
                                    {{ receiver.blood_group}}
                                </td>
                                <td>
                                    {{receiver.no_of_units_recieved}}
                                </td>
                                <td>
                                    {{receiver.date}}
                                </td>
                                <td>
                                    {{receiver.contact}}
                                </td> 
                                <td>
                                    {{receiver.email}}
                                </td>
                               
                                <td>
                                    <form action="{% url 'bloodbank:delete_receiver' receiver.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-trash"></i>
                                     </button>
                                     </form>
                                 </td>
                                 <td>
                                     <form action="{% url 'bloodbank:edit_receiver' receiver.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-edit"></i>
                                     </button>
                                     </form>
                                 </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

{% endblock %}