BloodBank/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name="bloodbank"

urlpatterns=[
    path('register/',views.UserCreate.as_view(),name="register"),
    path('',views.Index.as_view(),name="index"),

    #Donor Url
    path('view_donor',views.ViewDonor.as_view(),name="view_donor"),
    path('add_donor',views.AddDonor.as_view(),name='add_donor'),
    path('<int:pk>/delete_donor',views.DeleteDonor.as_view(),name='delete_donor'),
    path('<int:pk>/edit_donor',views.EditDonor.as_view(),name='edit_donor'),

    #Reciever Url
    path('view_receiver',views.ViewReceiver.as_view(),name="view_receiver"),
    path('add_receiver',views.AddReceiver.as_view(),name='add_receiver'),
    path('<int:pk>/delete_receiver',views.DeleteReceiver.as_view(),name='delete_receiver'),
    path('<int:pk>/edit_receiver',views.EditReceiver.as_view(),name='edit_receiver'),
    
    #Inventory Url
    path('view_inventory',views.ViewInventory.as_view(),name="view_inventory"),
    path('add_reviever',views.AddInventory.as_view(),name='add_inventory'),
    path('<int:pk>/delete_inventory',views.DeleteInventory.as_view(),name='delete_inventory'),
    path('<int:pk>/edit_inventory',views.EditInventory.as_view(),name='edit_inventory'),

]

HealthCare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myuser.urls')),
    path('ambulance/',include('Ambulance.urls')),
    path('bloodbank/',include('BloodBank.urls')),
    path('hospital/',include('Hospital.urls')),
    path('mdstore/',include('Medical_Store.urls')),
]

Medical_Store/urls.py
from django.urls import path
from . import views

app_name="Medical_Store"

urlpatterns=[
    path('register/',views.UserCreate.as_view(),name="register"),
    path('',views.Index.as_view(),name="index"),
    path('add_company/',views.AddCompany.as_view(),name="add_company"),

    #Inventory url
    path('add_medicine_inventory/',views.AddMedicine.as_view(),name="add_medicine_inventory"),
    path('view_medicine_inventory/',views.ViewMedicine.as_view(),name="view_medicine_inventory"),
    path('<int:pk>/delete_medicine_inventory',views.DeleteMedicine.as_view(),name='delete_medicine_inventory'),
    path('<int:pk>/edit_medicine_inventory',views.EditMedicine.as_view(),name='edit_medicine_inventory'),

    
    # path('/report/',views.reports,name="report"),
    # path('search/',views.search,name="search"),
    # path('serach/city/<slug:city>/',views.city_search,name="city_search"),
    # path('search/pincode/<int:pincode>/',views.pincode_search,name='pincode_search'),
    # path('search/medicine/<slug:medicine>/',views.medicine_search,name='medicine_search'),    
    # path('admin/',views.admin,name='admin'),
    # path('admin/add_medicine',views.add_medicine,name='add_medicine'),
    # path('admin/edit_medicine',views.edit_medicine,name='edit_medicine'),
    # path('admin/delete_medicine',views.delete_medicine,name='delete_medicine'),
    # path('admin/add_company',views.add_company,name='add_company'),
    # path('admin/edit_company',views.edit_company,name='edit_company'),
    # path('admin/delete_company',views.delete_company,name='delete_company'),
    # path('admin/store_details',views.store_details,name='store_details'),    
]

myuser/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name="myuser"

urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('search_ambulance', views.SearchAmbulance.as_view(),name='search_ambulance'),
    path('<int:pincode>/view_ambulance', views.ViewAmbulance.as_view(),name='view_ambulance'),
    path('search_hospital', views.SearchHospital.as_view(),name='search_hospital'),
    path('<int:pincode>/view_hospital', views.ViewHospital.as_view(),name='view_hospital'),
    path('search_bloodbank', views.ViewBloodbank.as_view(),name='search_bloodbank'),
    path('<int:pincode>/view_bloodbank', views.ViewBloodbank.as_view(),name='view_bloodbank'),
    path('search_medicine', views.SearchMedicine.as_view(),name='search_medicine'),
    path('<int:pincode>/view_medicine', views.ViewMedicine.as_view(),name='view_medicine'),
    path('register/',views.UserFormView.as_view(),name='register'),
    path('<pk>/delete',views.Delete.as_view(),name='delete'),
    path('logout/',views.LogoutView.as_view(),name='logout')
    # path('forgotpassword/',views.forgotpassword,name='forgotpasssword')
]

Medical_Store/models.py
from django.db import models
from myuser.models import Myuser,City
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
import datetime
from BloodBank.models import City

#Store Details
class Store_Details(models.Model):
    name=models.CharField(max_length=100)
    address=models.CharField(max_length=500)
    city=models.ForeignKey(City,on_delete=models.DO_NOTHING)
    pincode=models.PositiveIntegerField(validators=[MaxValueValidator(999999),MinValueValidator(100000)])
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)

#Company Name
class Company(models.Model):
    code=models.CharField(max_length=4,primary_key=True)
    name=models.CharField(max_length=100)
    address=models.CharField(max_length=500)
    city=models.ForeignKey(City,on_delete=models.DO_NOTHING)
    pincode=models.PositiveIntegerField(validators=[MaxValueValidator(999999),MinValueValidator(100000)])
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)


#Medicine Inventory
class Medicine_Inventory(models.Model):
    name=models.CharField(max_length=200)
    company_name=models.ForeignKey(Company,on_delete=models.CASCADE)
    mdf=models.DateField()
    expiry=models.DateField()
    mrp=models.PositiveIntegerField()
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)



# Create your models here.

Medical_Store/forms.py
from .models import *
from django import forms

class StoreDetails(forms.ModelForm):
    class Meta:
        model=Store_Details
        fields=['name','address','city','pincode','contact','user']
        exclude=('user',)

class CompanyDetails(forms.ModelForm):
    class Meta:
        model=Company
        fields=['code','name','address','city','pincode','contact','user']
        exclude=('user',)

class MedicineInventory(forms.ModelForm):
    class Meta:
        model=Medicine_Inventory
        fields=['name','company_name','mdf','expiry','mrp','user']
        exclude=('user',)

Medical_Store/views.py
from django.views.generic import *
from django.views.generic.edit import *
from .models import *
from django.urls import reverse_lazy,reverse
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from .forms import *
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

#Index Page
class Index(View):
    template_name='Medical_Store/layout.html'

    def get(self,request):
        return render(request,self.template_name)


class UserCreate(LoginRequiredMixin,View):
    form_class=StoreDetails
    template_name='Medical_Store/register.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return redirect('Medical_Store:index')
        
        return render(request,self.template_name,{'form':form})


class AddCompany(LoginRequiredMixin,View):
    form_class=CompanyDetails
    template_name='Medical_Store/add_company.html'
    #add_company.html ka template nahi bana hua

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return HttpResponse("<html>Company Added successfully</html>")
        
        return render(request,self.template_name,{'form':form})


class AddMedicine(LoginRequiredMixin,View):
    form_class=MedicineInventory
    template_name='Medical_Store/medicine_inventory_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return redirect('Medical_Store:view_medicine_inventory')
        
        return render(request,self.template_name,{'form':form})


#list medicines
class ViewMedicine(ListView):
    template_name='Medical_Store/medicine_inventory.html'
    context_object_name='medicine_inventory'
    model=Medicine_Inventory
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)


#edit medicine_inventory
class EditMedicine(UpdateView):
    model=Medicine_Inventory
    form_class=MedicineInventory
    template_name='Medical_Store/medicine_inventory_form.html'
    success_url=reverse_lazy('Medical_Store:view_medicine_inventory')

#Delete medicine_inventory
class DeleteMedicine(DeleteView):
    model=Medicine_Inventory
    success_url=reverse_lazy('Medical_Store:view_medicine_inventory')


# Create your views here.

templates/Medical_Store/add_inventory.html
{% extends 'Medical_Store/layout.html'%}
{% block title %} Inventory {% endblock %}
{% block body %}
    <div class="heading">
      		<h2>Inventory Details</h2>
      	</div>
      	<div class="custom-form">
                <form method="POST" action="">
                {% csrf_token%}
                    <label for="name">Name</label><br>
                    {{ form.name }}<br>
                    <label for="company">Company</label><br>
                    {{ form.company }}<br>
                    <label for="mfd">MFD</label><br>
                    {{ form.mfd }}<br>
                    <label for="expiry">Expiry</label><br>
                    {{ form.expiry }}<br>
                    <label for="mrp">MRP</label><br>
					{{ form.mrp }}<br>

					<input type="submit" name="Submit" id ="Submit" value="Submit">
                </form>
            </div>
{% endblock %}

templates/Medical_Store/base.html
<!DOCTYPE html>
<html>
    
<head>
	<title>{% block title %}{% endblock %}</title>
  {% load static  %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'myuser/css/register.css' %}"/>
  
</head>
<body>
	</head>
<body>
    <header>

        <a id="logo" href="#">
            <img src="{% static 'myuser/css/logo.png' %}" alt="Logo">
            <span>Frontida</span>
        </a>

        <nav>
            <ul>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </nav>

    </header>
    {{% block body %}
{% endblock %}}
</body>
</html>

templates/Medical_Store/inventory.html
{% extends 'Medical_Store/layout.html'%}
{% load static %}
{% block title %}Medicine Inventory{% endblock %}
{% block body %}
     <h3>Medicine Inventory</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <br><br><br>

                    <a href="{% url 'Medical_Store:add_inventory'%}">
                        <button type="button" class="btn btn-dark btn-group-small" height="45px">
                            Add 
                        </button>
                    </a>

                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th> Name</th>
                            <th>Company</th>
                            <th>MFD</th>
                            <th>Expiry</th>
                            <th>MRP</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for medicine in inventory %}
                            <tr>
                                <td>
                                    {{ medicine.name }}
                                </td>
                                <td>
                                    {{medicine.company}}
                                </td>
                                <td>
                                    {{medicine.mfd}}
                                </td>
                                <td>
                                    {{medicine.expiry}}
                                </td>
                                <td>
                                    {{medicine.mrp}}
                                </td>
                               
                                <td>
                                    <!--ek baar next line check karna ki medicine_inventory.id likhna hai ya only inventory.id-->
                                    <form action="{% url 'Medical_Store:delete_inventory' medicine.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-trash"></i>
                                     </button>
                                     </form>
                                 </td>
                                 <td>
                                     <form action="{% url 'Medical_Store:edit_inventory' medicine.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-edit"></i>
                                     </button>
                                     </form>
                                 </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

{% endblock %}

templates/Medical_Store/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"></head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Hospital/css/layout.css' %}"/>
<title>{% block title%} {% endblock %}</title>

</head>
<body>
	<div id="container">
    <div id="header">
        <header>
        <a href="{% url 'Medical_Store:index' %}">
            <img src="{% static 'myuser/css/logo.png' %}" alt="Logo" width="85">
        </a>
	 	<nav>
            <ul>
            	<li><a href="#">Home</a></li>
            	<li><a href="{% url 'myuser:logout' %}">LogOut</a></li>
                <div id="menuToggle">
    				<input type="checkbox" />
				    <span style="margin-top:-15px"></span>
				    <span></span>
				    <span></span>
				    <ul id="menu">
				      <a href="#"><li>Bloodbank</li></a><br>
				      <a href="#"><li>Hospital</li></a><br>
				      <a href="#"><li>Patient Record</li></a><br>
				      
				    </ul>
  				</div>
            </ul>
        </nav>
    </header>
    </div>
    <div id="content">
      <div id="columns-container">
      <div class="column column-a">
      		<div class="Services">
	        <article>
	            <h2>Hi XYZ Medical Store</h2>!</h2>
	            <div class="custom-form" style="margin-left:0px">
					<div id="cover">
					  <form method="get" action="">
					    <div class="tb">
						  <div class="td"><input type="text" placeholder="Search" onkeyup="search()" id="searchbar">
							</div>
					      <div class="td" id="s-cover">
					        <button type="submit">
					          <div id="s-circle"></div>
					          <span></span>
					        </button>
					      </div>
					    </div>
					  </form>
					</div>
	            </div>
	        </article>
	        	<div class="Cards">
	            <ul>
	                <li>
	                    <img src="{% static 'Medical_Store/medicine_inventory.jpg' %}" alt="medicine_inventory"><br><br><br>
	                    <a href="{% url 'Medical_Store:view_medicine_inventory'%}">Inventory</a>
	                </li>
	               
	            </ul>
	        	</div>
	    	</div>
      </div>
      <div class="column column-b">
	  {% block body %}
	  {% endblock %}
      </div>
      </div>
    </div>
</div>
</body>
</html>

templates/Medical_Store/medicine_inventory.html
{% extends 'Medical_Store/layout.html'%}
{% load static %}
{% block title %}Medicine Inventory{% endblock %}
{% block body %}
     <h3>Medicine Inventory</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <br><br><br>

                    <a href="{% url 'Medical_Store:add_medicine_inventory'%}">
                        <button type="button" class="btn btn-dark btn-group-small" height="45px">
                            Add 
                        </button>
                    </a>

                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th> Name</th>
                            <th>Company</th>
                            <th>MFD</th>
                            <th>Expiry</th>
                            <th>MRP</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for medicine in medicine_inventory %}
                            <tr>
                                <td>
                                    {{ medicine.name }}
                                </td>
                                <td>
                                    {{medicine.company_name}}
                                </td>
                                <td>
                                    {{medicine.mdf}}
                                </td>
                                <td>
                                    {{medicine.expiry}}
                                </td>
                                <td>
                                    {{medicine.mrp}}
                                </td>
                               
                                <td>
                                    <!--ek baar next line check karna ki medicine_inventory.id likhna hai ya only medicine_inventory.id-->
                                    <form action="{% url 'Medical_Store:delete_medicine_inventory' medicine.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-trash"></i>
                                     </button>
                                     </form>
                                 </td>
                                 <td>
                                     <form action="{% url 'Medical_Store:edit_medicine_inventory' medicine.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-edit"></i>
                                     </button>
                                     </form>
                                 </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

{% endblock %}

templates/Medical_Store/medicine_inventory_form.html
{% extends 'Medical_Store/layout.html'%}
{% block title %} Inventory {% endblock %}
{% block body %}
    <div class="heading">
      		<h2>Inventory Details</h2>
      	</div>
      	<div class="custom-form">
                <form method="POST" action="">
                {% csrf_token%}
                    <label for="name">Name</label><br>
                    {{ form.name }}<br>
                    <label for="company">Company</label><br>
                    {{ form.company_name }}<br>
                    <label for="mfd">MFD</label><br>
                    {{ form.mdf }}<br>
                    <label for="expiry">Expiry</label><br>
                    {{ form.expiry }}<br>
                    <label for="mrp">MRP</label><br>
					{{ form.mrp }}<br>

					<input type="submit" name="Submit" id ="Submit" value="Submit">
                </form>
            </div>
{% endblock %}

templates/Medical_Store/register.html
{% extends 'Medical_Store/base.html'%}
{% load static%}
{% block title%} Organisation Information {% endblock %}
{% block body%}
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Organisation Information</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
                    {% if error_message %}
                    <p><strong>{{error_message}}</strong></p>
                	{% endif  %}
					<form method="POST" action="">
					{% csrf_token %}
						<div class="input-group mb-3">
							<label for="name">Organisation Name  </label>
							{{ form.name }}
						</div>
						<div class="input-group mb-2">
							<label for="name">Address  </label>
							{{ form.address }}
						</div>
						<div class="input-group mb-2">
							<label for="name">City  </label>
							{{ form.city }}
						</div>
						<div class="input-group mb-2">
							<label for="name">Pincode  </label>
							{{ form.pincode }}
						</div>
                        <div class="input-group mb-2">
							<label for="name">Contact No </label>
							{{ form.contact }}
						</div>
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Submit">
				   		</div>
					</form>
				</div>
			</div>
		</div>
	</div>	
{% endblock%}