HealthCare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myuser.urls')),
    path('ambulance/',include('Ambulance.urls')),
    path('bloodbank/',include('BloodBank.urls')),
    path('hospital/',include('Hospital.urls')),
    path('mdstore/',include('Medical_Store.urls')),
]

Hospital/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from . import views
app_name="Hospital"

urlpatterns=[
    path('register/',views.UserCreate.as_view(),name="register"),
    path('',views.Index.as_view(),name="index"),

    #Doctor Url
    path('view_doctor/',views.ViewDoctor.as_view(),name="view_doctor"),
    path('add_doctor',views.AddDoctor.as_view(),name='add_doctor'),
    path('<int:pk>/delete_doctor',views.DeleteDoctor.as_view(),name='delete_doctor'),
    path('<int:pk>/edit_doctor',views.EditDoctor.as_view(),name='edit_doctor'),

    #Patient Url
    path('view_patient/',views.ViewPatient.as_view(),name="view_patient"),
    path('add_patient',views.AddPatient.as_view(),name='add_patient'),
    path('<int:pk>/delete_patient',views.DeletePatient.as_view(),name='delete_patient'),
    path('<int:pk>/edit_patient',views.EditPatient.as_view(),name='edit_patient'),
   
    #Test Url
    path('view_test/',views.ViewTest.as_view(),name="view_test"),
    path('add_test',views.AddTest.as_view(),name='add_test'),
    path('<int:pk>/delete_test',views.DeleteTest.as_view(),name='delete_test'),
    path('<int:pk>/edit_test',views.EditTest.as_view(),name='edit_test'),

    #Conducted Url
    path('view_conducted/',views.ViewConducted.as_view(),name="view_conducted"),
    path('add_conducted',views.AddConducted.as_view(),name='add_conducted'),
    path('<int:pk>/delete_conducted',views.DeleteConducted.as_view(),name='delete_conducted'),
    path('<int:pk>/edit_conducted',views.EditConducted.as_view(),name='edit_conducted'),
    
]

myuser/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name="myuser"

urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('search_ambulance', views.SearchAmbulance.as_view(),name='search_ambulance'),
    path('<int:pincode>/view_ambulance', views.ViewAmbulance.as_view(),name='view_ambulance'),
    path('search_hospital', views.SearchHospital.as_view(),name='search_hospital'),
    path('<int:pincode>/view_hospital', views.ViewHospital.as_view(),name='view_hospital'),
    path('search_bloodbank', views.ViewBloodbank.as_view(),name='search_bloodbank'),
    path('<int:pincode>/view_bloodbank', views.ViewBloodbank.as_view(),name='view_bloodbank'),
    path('search_medicine', views.SearchMedicine.as_view(),name='search_medicine'),
    path('<int:pincode>/view_medicine', views.ViewMedicine.as_view(),name='view_medicine'),
    path('register/',views.UserFormView.as_view(),name='register'),
    path('<pk>/delete',views.Delete.as_view(),name='delete'),
    path('logout/',views.LogoutView.as_view(),name='logout')
    # path('forgotpassword/',views.forgotpassword,name='forgotpasssword')
]

Hospital/models.py
from django.db import models
from myuser.models import Myuser,City
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
import datetime
# Create your models here.

class Hosp_detail(models.Model):
    name=models.CharField(max_length=25)
    address=models.CharField(max_length=500)
    city=models.ForeignKey(City,on_delete=models.DO_NOTHING)
    pincode=models.PositiveIntegerField(validators=[MaxValueValidator(999999),MinValueValidator(100000)])
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    email=models.EmailField(max_length=50)
    emergency_contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999), MinValueValidator(1000000000)])
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)


class Days(models.Model):
    day = models.CharField(max_length=12)

    def __str__(self):
        return self.day


class Doctor(models.Model):
    name=models.CharField(max_length=25)
    speciality=models.CharField(max_length=200)
    qualification=models.CharField(max_length=10)
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    starting_time=models.TimeField(auto_now=False, auto_now_add=False)
    ending_time=models.TimeField(auto_now=False, auto_now_add=False)
    working_days= models.ManyToManyField(Days)
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('Hospital:view_doctor')
    
    
class Patient(models.Model):
    name=models.CharField(max_length=200)
    dob=models.DateField(auto_now=False, auto_now_add=False)
    gender=models.CharField(max_length=10)
    blood_group=models.CharField(max_length=15)
    med_history=models.CharField(max_length=1000)
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    adm_date=models.DateField(auto_now=False, auto_now_add=False)
    discharge_date=models.DateField(auto_now=False, auto_now_add=False)  
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)
    
class Tests(models.Model):
    test_id = models.CharField(max_length=5)
    name=models.CharField(max_length=20)
    test_type=models.CharField(max_length=30)
    cost=models.IntegerField(blank=False)
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)
    
class Conducted(models.Model):
    diagnosis = models.CharField(max_length=1000)
    report=models.TextField()
    test=models.ForeignKey(Tests,on_delete=models.CASCADE)
    patient=models.ForeignKey(Patient,on_delete=models.CASCADE)
    date=models.DateField(auto_now=False, auto_now_add=False)
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)

Hospital/forms.py
from .models import *
from django import forms
from django.forms import widgets

class TimeInput(forms.TimeInput):
    input_type="time"

class HospDetail(forms.ModelForm):
    class Meta:
        model=Hosp_detail
        fields = ['name', 'address','city','pincode','contact', 'email', 'emergency_contact', 'user']
        exclude=('user',)



class DoctorDetails(forms.ModelForm):
    widgets={'day':forms.CheckboxSelectMultiple}
    contact =forms.CharField(max_length=10)
    starting_time=forms.TimeField(widget=TimeInput)
    ending_time=forms.TimeField(widget=TimeInput)
    class Meta:
        model=Doctor
        fields = ['name', 'speciality', 'qualification', 'contact', 'starting_time','ending_time', 'working_days', 'user']
        exclude=('user',)



class PatientDetails(forms.ModelForm):
    class Meta:
        model=Patient
        fields = ['name', 'dob', 'gender', 'blood_group', 'med_history', 'contact', 'adm_date', 'discharge_date', 'user']
        exclude=('user',)
        
class TestDetails(forms.ModelForm):
    class Meta:
        model=Tests
        fields = ['test_id', 'name', 'test_type', 'cost', 'user']
        exclude = ('user',)

class TestConducted(forms.ModelForm):
    class Meta:
        model=Conducted
        fields = ['diagnosis', 'report', 'test', 'patient', 'date','user']
        exclude = ('user',)

Hospital/views.py
from django.views.generic import *
from django.views.generic.edit import *
from .models import *
from django.urls import reverse_lazy,reverse
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from .forms import *
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

#User Registration Details
class UserCreate(LoginRequiredMixin,View):
    form_class=HospDetail
    template_name='Hospital/register.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            print(provider.name)
            provider.user = self.request.user
            provider.save()
            return redirect('Hospital:index')
        
        return render(request,self.template_name,{'form':form})

# Index views
class Index(View):
    template_name='Hospital/layout.html'

    def get(self,request):
        return render(request,self.template_name)


#Doctor's Views
#Add Doctor's details
class AddDoctor(LoginRequiredMixin,View):
    form_class=DoctorDetails
    template_name='Hospital/doctor_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return redirect('Hospital:view_doctor')
        
        return render(request,self.template_name,{'form':form})

#View Doctor
class ViewDoctor(ListView):
    template_name='Hospital/doctor.html'
    context_object_name='doctors'
    model=Doctor
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)


class EditDoctor(UpdateView):
    model=Doctor
    form_class=DoctorDetails
    template_name='Hospital/doctor_form.html'
    success_url=reverse_lazy('Hospital:view_doctor')

#Delete Doctor
class DeleteDoctor(DeleteView):
    model=Doctor
    success_url=reverse_lazy('Hospital:view_doctor')

#Patient Record
# Add Patient's Records
class AddPatient(LoginRequiredMixin,View):
    form_class=PatientDetails
    template_name='Hospital/patient_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return redirect('Hospital:view_patient')
        
        return render(request,self.template_name,{'form':form})

#View Patient
class ViewPatient(ListView):
    template_name='Hospital/patient.html'
    context_object_name='patients'
    model=Patient
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)

#Edit Patient(still to be updated)
class EditPatient(UpdateView):
    model=Patient
    form_class=PatientDetails
    template_name='Hospital/patient_form.html'
    success_url=reverse_lazy('Hospital:view_patient')

#Delete Patient
class DeletePatient(DeleteView):
    model=Patient
    success_url=reverse_lazy('Hospital:view_patient')

# Test Available
# Test details
class AddTest(LoginRequiredMixin,View):
    form_class=TestDetails
    template_name='Hospital/test_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return redirect('Hospital:view_test')
        
        return render(request,self.template_name,{'form':form})

#View Tests
class ViewTest(ListView):
    template_name='Hospital/test.html'
    context_object_name='tests'
    model=Tests
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)

#Edit Tests(still to be updated)
class EditTest(UpdateView):
    model=Tests
    form_class=TestDetails
    template_name='Hospital/test_form.html'
    success_url=reverse_lazy('Hospital:view_test')

#Delete Tests
class DeleteTest(DeleteView):
    model=Tests
    success_url=reverse_lazy('Hospital:view_test')


#Test Conducted
# Patient Test Conducted 
class AddConducted(LoginRequiredMixin,View):
    form_class=TestConducted
    template_name='Hospital/conducted_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            form.instance.user = self.request.user
            provider.save()
            return redirect('Hospital:view_conducted')
        
        return render(request,self.template_name,{'form':form})

#View Conducted
class ViewConducted(ListView):
    template_name='Hospital/conducted.html'
    context_object_name='conducted'
    model=Conducted
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)

#Edit Conducted(still to be updated)
class EditConducted(UpdateView):
    model=Conducted
    form_class=TestConducted
    template_name='Hospital/conducted_form.html'
    success_url=reverse_lazy('Hospital:view_conducted')

#Delete Conducted
class DeleteConducted(DeleteView):
    model=Conducted
    success_url=reverse_lazy('Hospital:view_conducted')

# Create your views here.

templates/Hospital/base.html
<!DOCTYPE html>
<html>
    
<head>
{% load static  %}
	<title>{% block title %}{% endblock %}</title>
    
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'myuser/css/register.css' %}"/>
  
</head>

<body>
    <header>

        <a id="logo" href="#">
            <img src="{% static 'myuser/css/logo.png' %}" alt="Logo">
            <span>Frontida</span>
        </a>

        <nav>
            <ul>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </nav>

    </header>
    {{% block body %}
{% endblock %}}
</body>
</html>

templates/Hospital/doctor.html
{% extends 'Hospital/layout.html'%}
{% load static %}
{% block title %}Doctors{% endblock %}
{% block body %}
     <h3>Doctors</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <br><br><br>
                   
                    <a href="{% url 'Hospital:add_doctor'%}">
                                                <button type="button" class="btn btn-dark btn-group-small" height="45px">
                                                    Add 
                                                </button>
                                            </a>
                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Specialist</th>
                            <th>Contact</th>
                            <th>Clinic Timings</th>
                            <th>Working Days</th>
                            <th>Delete</th>
                            <th>Edit</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for doctor in doctors %}
                            <tr>
                                <td>
                                {{ doctor.name }}</td>
                                <td>
                                    {{ doctor.speciality}}
                                </td>
                                <td>
                                    {{doctor.contact}}
                                </td>
                                <td>
                                    {{doctor.starting_time}} to {{doctor.ending_time}}
                                </td> 
                                <td>
                                    {{doctor.working_days}}
                                </td>
                                <td>
                                   <form action="{% url 'Hospital:delete_doctor' doctor.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{ album.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                    <i class="fas fa-trash"></i>
                                    </button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{% url 'Hospital:edit_doctor' doctor.id %}" method="get" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{ album.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                    <i class="fas fa-edit"></i>
                                    </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

{% endblock %}

templates/Hospital/doctor_form.html
{% extends 'Hospital/layout.html'%}
{% block title %} Doctor Registration {% endblock %}
{% block body %}
    <div class="heading">
      		<h2>Doctor Details</h2>
      	</div>
      	<div class="custom-form">
                <form method="POST" action="">
				{% csrf_token%}
                	<label for="name">Name</label><br>
                    {% comment %} <input type="text" name="name" id="name" placeholder="Name"><br> {% endcomment %}
					{{ form.name}}<br>
                    <label for="qualification">Qualification</label><br>
					{{ form.qualification }}<br>
                    {% comment %} <input type="text" name="qualification" id="qualification" placeholder="Qualification"><br> {% endcomment %}
                    <label for="specialist">Specialist</label><br>
					{{form.speciality}}<br>
                    {% comment %} <input type="text" name="specialist" id="specialist" placeholder="Specialist"><br> {% endcomment %}
                    <label for="contact">Contact</label><br>
					{{ form.contact }}<br>
                    {% comment %} <input type="text" name="contact" id="contact" placeholder="Contact Number"><br> {% endcomment %}

                    <label for="appt">Consulting time</label><br>
  					<label for="time" id="time">From:</label>{{form.starting_time}}
					{% comment %} <input type="time" id="from" name="from"> {% endcomment %}
  					<label for="time">To:  </label>{{form.ending_time}}
					{% comment %} <input type="time" id="to" name="to"> {% endcomment %}
  					<br>
                    
                    <label for="days">Number of Days</label><br>
					{{ form.working_days}}
					    {% comment %} <select id="number" name="number">
					      <option value="1">1</option>
					      <option value="2">2</option>
					      <option value="3">3</option>
					    </select> {% endcomment %}

					    <br><br>

					<input type="submit" name="Submit" id ="Submit" value="Submit">
                </form>
            </div>
{% endblock %}

templates/Hospital/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"></head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Hospital/css/layout.css' %}"/>
<title>{% block title%} {% endblock %}</title>

</head>
<body>
	<div id="container">
    <div id="header">
        <header>
        <a href="{% url 'Hospital:index' %}">
            <img src="{% static 'myuser/css/logo.png' %}" alt="Logo" width="85">
        </a>
	 	<nav>
            <ul>
            	<li><a href="#">Home</a></li>
            	<li><a href="{% url 'myuser:logout' %}">LogOut</a></li>
                <div id="menuToggle">
    				<input type="checkbox" />
				    <span style="margin-top:-15px"></span>
				    <span></span>
				    <span></span>
				    <ul id="menu">
				      <a href="#"><li>Medical Store</li></a><br>
				      <a href="#"><li>Blood Bank</li></a><br>
				      <a href="#"><li>Patient Record</li></a><br>
				      
				    </ul>
  				</div>
            </ul>
        </nav>
    </header>
    </div>
    <div id="content">
      <div id="columns-container">
      <div class="column column-a">
      		<div class="Services">
	        <article>
	            <h2>Hi XYZ Hospital!</h2>
	            <div class="custom-form" style="margin-left:0px">
					<div id="cover">
					  <form method="get" action="">
					    <div class="tb">
					      <div class="td"><input type="text" placeholder="Search"></div>
					      <div class="td" id="s-cover">
					        <button type="submit">
					          <div id="s-circle"></div>
					          <span></span>
					        </button>
					      </div>
					    </div>
					  </form>
					</div>
	            </div>
	        </article>
	        	<div class="Cards">
	            <ul>
	                <li>
	                    <img src="{% static 'Hospital/hospital.jpg' %}" alt="hospital"><br><br><br>
	                    <a href="#">Hospital</a>
	                </li>
	                <li>
	                    <a href="{% url 'Hospital:view_doctor'%}"><img src="{% static 'Hospital/doctor.jpg' %}" alt="doctor"></a><br><br><br>
	                    <a href="{% url 'Hospital:view_doctor'%}">Doctors</a>
					</li>
				</ul>
				</div>
				<div class="Cards">
				<ul>
					<li>
	                    <a href="{% url 'Hospital:view_test'%}"><img src="{% static 'Hospital/test.jpg' %}" alt="test"></a><br><br><br>
	                    <a href="{% url 'Hospital:view_test'%}">Tests</a>
					</li>
					<li>
	                    <a href="{% url 'Hospital:view_patient'%}"><img src="{% static 'Hospital/patient.jpg' %}" alt="doctor"></a><br><br><br>
	                    <a href="{% url 'Hospital:view_patient'%}">Patients</a>
	                </li>
				</ul>
				<ul>
	                <li>
	                    <img src="{% static 'Hospital/test.jpg' %}" alt="test"><br><br><br>
	                    <a href="{% url 'Hospital:view_test'%}">Tests</a>
	                </li>
	                <li>
	                    <img src="{% static 'Hospital/patient.jpg' %}" alt="patient"><br><br><br>
	                    <a href="{% url 'Hospital:view_patient'%}">Patients</a>
	                </li>
	            </ul>
	        	</div>
	    	</div>
      </div>
      <div class="column column-b">
	  {% block body %}
	  {% endblock %}
      </div>
      </div>
    </div>
</div>
</body>
</html>

templates/Hospital/patient.html
{% extends 'Hospital/layout.html'%}
{% load static %}
{% block title %}Patients{% endblock %}
{% block body %}
     <h3>Doctors</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <br><br><br>

                    <a href="{% url 'Hospital:add_patient'%}">
                        <button type="button" class="btn btn-dark btn-group-small" height="45px">
                            Add 
                        </button>
                    </a>

                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>DOB</th>
                            <th>Gender</th>
                            <th>Blood group</th>
                            <th>Medical history</th>
                            <th>Contact</th>
                            <th>Admission date</th>
                            <th>Discharge date</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for patient in patients %}
                            <tr>
                                <td>
                                    {{ patient.name }}
                                </td>
                                <td>
                                    {{ patient.dob}}
                                </td>
                                <td>
                                    {{patient.gender}}
                                </td>
                                <td>
                                    {{patient.blood_group}}
                                </td>
                                <td>
                                    {{patient.med_history}}
                                </td> 
                                <td>
                                    {{patient.contact}}
                                </td>
                                <td>
                                    {{patient.adm_date}}
                                </td>
                                <td>
                                    {{patient.discharge_date}}
                                </td>
                                
                                <td>
                                    <form action="{% url 'Hospital:delete_patient' patient.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-trash"></i>
                                     </button>
                                     </form>
                                 </td>
                                 <td>
                                     <form action="{% url 'Hospital:edit_patient' patient.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-edit"></i>
                                     </button>
                                     </form>
                                 </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

{% endblock %}

templates/Hospital/test.html
{% extends 'Hospital/layout.html'%}
{% load static %}
{% block title %}Tests{% endblock %}
{% block body %}
     <h3>Tests</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <br><br><br>
                    
                    <a href="{% url 'Hospital:add_test'%}">
                        <button type="button" class="btn btn-dark btn-group-small" height="45px">
                            Add 
                        </button>
                    </a>
                    
                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th>Test ID</th>
                            <th>Test name</th>
                            <th>Test type</th>
                            <th>Cost</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for test in tests %}
                            <tr>
                                <td>
                                    {{ test.test_id }}
                                </td>
                                <td>
                                    {{ test.name }}
                                </td>
                                <td>
                                    {{ test.test_type }}
                                </td>
                                <td>
                                    {{test.cost}}
                                </td>
                                
                                <td>
                                    <form action="{% url 'Hospital:delete_test' test.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-trash"></i>
                                     </button>
                                     </form>
                                 </td>
                                 <td>
                                     <form action="{% url 'Hospital:edit_test' test.id %}" method="post" style="display: inline;">
                                     {% csrf_token %}
                                     <input type="hidden" name="album_id" value="{{ album.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                     <i class="fas fa-edit"></i>
                                     </button>
                                     </form>
                                 </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

{% endblock %}