Ambulance/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from . import views
app_name="Ambulance"

urlpatterns=[
    path('',views.Index.as_view(),name="index"),
    path('register/',views.UserCreate.as_view(),name="register"),
    # Ambulance Servicce
    path('add_ambulance/',views.AddAmbulance.as_view(),name="add_ambulance"),
    path('<int:pk>/edit_ambulance/',views.EditAmbulance.as_view(),name="edit_ambulance"),
    path('<int:pk>/delete_ambulance/',views.DeleteAmbulance.as_view(),name="delete_ambulance"),
    path('view_ambulance/',views.ViewAmbulance.as_view(),name="view_ambulance"),
    # path('/report/',views.reports,name="report"),
    # path('search/',views.search,name="search"),
    # path('search/pincode/<slug:pincode>/',views.pincode_search,name="pincode_search"),
    # path('admin/',views.admin,name='admin'),
    # path('admin/edit_ambulance',views.edit_ambulance,name='edit_ambulance'),
    # path('admin/delete_ambulance',views.delete_ambulance,name='delete_ambulance'),
    # path('admin/provider_detail',views.provider_detail,name='provider_detail'),

]

HealthCare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myuser.urls')),
    path('ambulance/',include('Ambulance.urls')),
    path('bloodbank/',include('BloodBank.urls')),
    path('hospital/',include('Hospital.urls')),
    path('mdstore/',include('Medical_Store.urls')),
]

myuser/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
app_name="myuser"

urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('search_ambulance', views.SearchAmbulance.as_view(),name='search_ambulance'),
    path('<int:pincode>/view_ambulance', views.ViewAmbulance.as_view(),name='view_ambulance'),
    path('search_hospital', views.SearchHospital.as_view(),name='search_hospital'),
    path('<int:pincode>/view_hospital', views.ViewHospital.as_view(),name='view_hospital'),
    path('search_bloodbank', views.ViewBloodbank.as_view(),name='search_bloodbank'),
    path('<int:pincode>/view_bloodbank', views.ViewBloodbank.as_view(),name='view_bloodbank'),
    path('search_medicine', views.SearchMedicine.as_view(),name='search_medicine'),
    path('<int:pincode>/view_medicine', views.ViewMedicine.as_view(),name='view_medicine'),
    path('register/',views.UserFormView.as_view(),name='register'),
    path('<pk>/delete',views.Delete.as_view(),name='delete'),
    path('logout/',views.LogoutView.as_view(),name='logout')
    # path('forgotpassword/',views.forgotpassword,name='forgotpasssword')
]

Ambulance/models.py
from django.db import models
from myuser.models import Myuser,City
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
import datetime

AMB_CHOICES=(
    ('MAB','Mini Ambulance'),
    ('FAB','Fully Equiped Ambulance'),
)
# Service Provider
class Service_Provider(models.Model):
    name=models.CharField(max_length=256)
    city=models.ForeignKey(City,on_delete=models.DO_NOTHING)
    address=models.CharField(max_length=500)
    pincode=models.PositiveIntegerField(validators=[MaxValueValidator(999999),MinValueValidator(100000)])
    no_of_ambulances=models.IntegerField(default=1)
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)

#Ambulance Details
class Ambulance(models.Model):
    vehicle_no=models.CharField(max_length=15,unique=True)
    user=models.ForeignKey(Myuser,on_delete=models.CASCADE)
    name=models.CharField(max_length=256)
    city=models.ForeignKey(City,on_delete=models.DO_NOTHING)
    pincode=models.PositiveIntegerField(validators=[MaxValueValidator(999999),MinValueValidator(100000)])
    contact=models.PositiveIntegerField(validators=[MaxValueValidator(9999999999),MinValueValidator(1000000000)])
    amb_type=models.CharField(max_length=3,choices=AMB_CHOICES)



# Create your models here.

myuser/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
USER_CHOICE=[
    ('AMB','Ambulance'),
    ('BLB','Blood-Bank'),
    ('HSP','Hospital'),
    ('MST','Medical-Store'),
]

class Myusermanager(BaseUserManager):
    def create_user(self,email,password=None):
        if not email:
            raise ValueError("User must have an email")
        
        user=self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,password):
        user=self.create_user(
            email=self.normalize_email(email),
            password=password,
        )
        user.is_admin=True
        user.is_staff=True
        user.is_superuser=True
        user.save(using=self.db)
        return user


class Myuser(AbstractBaseUser):
    email=models.EmailField(max_length=256,verbose_name="email",unique=True)
    user_type=models.CharField(max_length=3,choices=USER_CHOICE)
    date_joined=models.DateTimeField(verbose_name='date-joined',auto_now_add=True)
    last_login=models.DateTimeField(verbose_name='last-login',auto_now=True)
    is_admin=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)
    is_staff=models.BooleanField(default=False)
    is_superuser=models.BooleanField(default=False)

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=[]

    objects=Myusermanager()

    def __str__(self):
        return self.email

    def has_perm(self,perm,obj=None):
        return self.is_admin

    def has_module_perms(self,app_label):
        return True

class City(models.Model):
    std_code=models.PositiveIntegerField(validators=[MaxValueValidator(9999),MinValueValidator(1000)])
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

# Create your models here.

Ambulance/forms.py
from django import forms
from .models import *

class ServiceProvider(forms.ModelForm):
    class Meta:
        model = Service_Provider
        fields=['name', 'city', 'address', 'pincode', 'no_of_ambulances', 'contact', 'user']
        exclude=('user',)
        
class AmbulanceDetails(forms.ModelForm):
    class Meta:
        model = Ambulance
        fields=['vehicle_no', 'user', 'name', 'city', 'pincode', 'contact', 'amb_type']
        exclude=('user',)

myuser/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Myuser,City

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    password2=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Myuser
        fields=['email','password','password2','user_type']

class LoginForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=Myuser
        fields=['email','password']

class CityAdd(forms.ModelForm):
    class Meta:
        model=City
        fields=['std_code','name']

Ambulance/views.py
from django.views.generic import *
from django.views.generic.edit import *
from .models import *
from django.urls import reverse_lazy,reverse
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from .forms import *
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

#Index Page
class Index(View):
    template_name='Ambulance/layout.html'

    def get(self,request):
        return render(request,self.template_name)


class UserCreate(LoginRequiredMixin,View):
    form_class=ServiceProvider
    template_name='Ambulance/register.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            provider.user = self.request.user
            provider.save()
            return redirect("Ambulance:index")
        
        return render(request,self.template_name,{'form':form})

class AddAmbulance(LoginRequiredMixin,View):
    form_class=AmbulanceDetails
    template_name='Ambulance/ambulance_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            provider=form.save(commit=False)
            provider.user = self.request.user
            provider.save()
            #redirect to home page
            return redirect("Ambulance:view_ambulance")
        
        return render(request,self.template_name,{'form':form})

#View Doctor
class ViewAmbulance(ListView):
    template_name='Ambulance/ambulance.html'
    context_object_name='ambulance_details'
    model=Ambulance
    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user is None:
            return qs
        return qs.filter(user=user)


class EditAmbulance(UpdateView):
    model=Ambulance
    form_class=AmbulanceDetails
    template_name='Ambulance/ambulance_form.html'
    success_url=reverse_lazy('Ambulance:view_ambulance')

#Delete Doctor
class DeleteAmbulance(DeleteView):
    model=Ambulance
    success_url=reverse_lazy('Ambulance:view_ambulance')

# Create your views here.

myuser/views.py
from django.views.generic import *
from django.views.generic.edit import *
from .models import *
from django.urls import reverse_lazy,reverse
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from .forms import *
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from Medical_Store.models import * 
from Ambulance.models import *
from BloodBank.models import *
from Hospital.models import *

class Index(View):
    template_name='myuser/home.html'

    def get(self,request):
        return render(request,self.template_name)

class SearchMedicine(View):
    template_name='myuser/search_medicine.html'

    def get(self,request):
        return render(request,self.template_name)

class SearchAmbulance(View):
    template_name='myuser/search_ambulance.html'

    def get(self,request):
        return render(request,self.template_name)

class SearchHospital(View):
    template_name='myuser/search_hopital.html'

    def get(self,request):
        return render(request,self.template_name)

class SearchBloodBank(View):
    template_name='myuser/search_bloodbank.html'

    def get(self,request):
        return render(request,self.template_name)

class ViewMedicine(ListView):
    template_name='myuser/medicine.html'
    context_object_name='medical'
    model=Store_Details
    def get_queryset(self):
        qs = super().get_queryset()
        pincode = self.request.pincode
        if pincode is None:
            return qs
        return qs.filter(pincode=pincode)

class ViewAmbulance(ListView):
    template_name='myuser/ambulance.html'
    context_object_name='ambulance_details'
    model=Service_Provider
    def get_queryset(self):
        qs = super().get_queryset()
        pincode = self.request.pincode
        if pincode is None:
            return qs
        return qs.filter(pincode=pincode)


class ViewHospital(ListView):
    template_name='myuser/hospital.html'
    context_object_name='hospital_details'
    model=Hosp_detail
    def get_queryset(self):
        qs = super().get_queryset()
        pincode = self.request.pincode
        if pincode is None:
            return qs
        return qs.filter(pincode=pincode)


class ViewBloodbank(ListView):
    template_name='myuser/bloodbank.html'
    context_object_name='bb_details'
    model=BB_Details
    def get_queryset(self):
        qs = super().get_queryset()
        pincode = self.request.pincode
        if pincode is None:
            return qs
        return qs.filter(pincode=pincode)

class UserFormView(View):
    form_class=UserForm
    template_name='myuser/registration_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            user_type=form.cleaned_data['user_type']
            password2=form.cleaned_data['password2']
            if password==password2:
                user.set_password(password)
                user.save()
                user=authenticate(email=email,password=password)
                if user is not None:
                    if user.is_active:
                        login(request,user)
                        if user_type=="AMB":
                            return redirect('Ambulance:register')
                        elif user_type=="HSP":
                            return redirect('Hospital:register')
                        elif user_type=="MST":
                            return redirect('Medical_Store:register')
                        elif user_type=="BLB":
                            return redirect('bloodbank:register')
                        else:
                            return render(request,self.template_name,{'form':form})  
            
        form=self.form_class(None)      
        return render(request,self.template_name,{'form':form})

class LoginView(View):
    #use formset and refer sibtc
    form_class=LoginForm
    template_name='myuser/login.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})


    def post(self,request):
        form=self.form_class(request.POST)
        email=request.POST['email']
        password=request.POST['password']
        print(email)
        user=authenticate(email=email,password=password)
        user_details=Myuser.objects.get(email=email)
        user_type=user_details.user_type
        
        if user is not None:
            if user.is_active:
                login(request,user)
                if user_type=="HSP" :
                    #return HttpResponse("<html>Welcome to Ambulance</html>")
                    return redirect('Hospital:index')
                    
                elif user_type=="AMB" :
                    #return HttpResponse("<html>Welcome to Ambulance</html>")
                    return redirect('Ambulance:index')

                elif user_type=="BLB" :
                    #return HttpResponse("<html>Welcome to BLoodBank</html>")
                    return redirect('bloodbank:index')
                elif user_type=="MST":
                    return redirect('Medical_Store:index')

                    #return HttpResponse("<html>Welcome to Medical Store</html>")
                    #return redirect('Attendance_manager:index_student')
                else :
                    return HttpResponse("</html>Not Selected valid user type</html>")
                   # return redirect('Attendance_manager:mark_attendance')
                #messages.info(request, 'Your have successfully loged in!')
                #return redirect('myuser:login')
            else:
                return render(request, 'myuser/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'myuser/login.html', {'form':form,'error_message': 'Invalid login'})
        return render(request,self.template_name,{'form':form})

class LogoutView(View):
    form_class=LoginForm
    template_name='myuser/login.html'
    def get(self,request):
        form=self.form_class(None)
        logout(request)
        return redirect(reverse('myuser:login'))

class Delete(DeleteView):
    model=Myuser
    success_url=reverse_lazy('myuser:login')

templates/myuser/ambulance.html
<html>
<head>
<title>
Search Ambulance
</title>
</head>
<body>
                    <table class="table" align="center">
                        <thead>
                        <tr>
                            <th> Vehicle number</th>
                            <th>Name</th>
                            <th>City</th>
                            <th>Pincode</th>
                            <th>Contact</th>
                            <th>Ambulance type</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ambulance in ambulance_details %}
                            <tr>
                                <td>
                                    {{ ambulance.vehicle_no }}
                                </td>
                                <td>
                                    {{ambulance.name}}
                                </td>
                                <td>
                                    {{ambulance.city}}
                                </td>
                                <td>
                                    {{ambulance.pincode}}
                                </td>
                                <td>
                                    {{ambulance.contact}}
                                </td>
                                <td>
                                    {{ambulance.amb_type}}
                                </td>
                                </tr>
                                </tbody>
                                </table>
</body>
</html>

templates/myuser/base.html
<!DOCTYPE html>
<html>
    
<head>
	<title>{% block title %}{% endblock %}</title>
  {% load static  %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'myuser/css/login.css' %}"/>
  
</head>
<body>
	</head>
<body>
    <header>

        <a id="logo" href="#">
            <img src="{% static 'myuser/css/logo.png' %}" alt="Logo">
            <span>Frontida</span>
        </a>

        <nav>
            <ul>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </nav>

    </header>
    {{% block body %}
{% endblock %}}
</body>
</html>

templates/myuser/home.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>Frontida</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'myuser/css/main.css'%}" />
		<noscript>
		<link rel="stylesheet" href="{% static 'myuser/css/noscript.css'%}" />
		</noscript>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body class="is-preload">
			<div id="wrapper">

					<header id="header">
						<div class="inner">

								<a href="#" class="logo">
									<span class="symbol"><img src="{%static 'myuser/images/logo.png'}" alt="" /></span>
								</a>

								<nav>
									<ul>
										<li><a href="#">Home</a></li>
										<li><a href="{% url 'myuser:login'%}">Login</a></li>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="#">Medical Store</a></li>
							<li><a href="#">Blood Bank</a></li>
							<li><a href="#">Ambulance Service</a></li>
						</ul>
					</nav>

					<div id="main">
						<div class="inner">
							<header>
								<h1>Frontida</h1>
								<p>HealthCare at your door steps.<br>frontida@gmail.com | +91 69420 69420</p>
							</header>
							<section class="tiles">
								<article class="style1">
									<span class="image">
										<img src="{% static 'myuser/images/pic01.jpg'%}" alt="" />
									</span>
									<a href="{% url 'myuser:search_hospital' %}">
										<h2>Hospital</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style2">
									<span class="image">
										<img src="{% static 'myuser/images/pic03.jpg'%}" alt="" />
									</span>
									</a>
									<a href="{% url 'myuser:search_ambulance'%}">
										<h2>Ambulance</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								<article class="style">
									<span class="image">
										<img src="{% static 'myuser/images/pic01.jpg'%}" alt="" />
									</span>
									<a href="{% url 'myuser:search_medicine' %}"
										<h2>Medicine</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								{% comment %} <article class="style1">
									<span class="image">
										<img src="{% static 'myuser/images/pic04.jpg'%}" alt="" />
									</span>
									<a href="{% url 'myuser:search_bloodbank'%}>
										<h2>Blood Bank</h2>
										<div class="content">
											<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
										</div>
									</a>
								</article>
								 {% endcomment %}
							</section>
						</div>
					</div>

					<footer id="footer">
						<div class="inner">
							<section>
								<h2>Get in touch</h2>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<input type="text" name="name" id="name" placeholder="Name" />
										</div>
										<div class="field half">
											<input type="email" name="email" id="email" placeholder="Email" />
										</div>
										<div class="field">
											<textarea name="message" id="message" placeholder="Message"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send" class="primary" /></li>
									</ul>
								</form>
							</section>
							<section>
								<h2>Follow</h2>
								<ul class="icons">
									<a href="#" class="fa fa-facebook"></a>
									<a href="#" class="fa fa-twitter"></a>
									<a href="#" class="fa fa-google"></a>
									<a href="#" class="fa fa-linkedin"></a>
									<a href="#" class="fa fa-youtube"></a>
									<a href="#" class="fa fa-instagram"></a>
									<a href="#" class="fa fa-pinterest"></a>
								</ul>
							</section>
							<ul class="copyright">
								<li>&copy; Frontida. All rights reserved</li>
							</ul>
						</div>
					</footer>

			</div>

			<script src="{% static 'myuser/js/jquery.min.js'%}"></script>
			<script src="{% static 'myuser/js/browser.min.js'%}"></script>
			<script src="{% static 'myuser/js/breakpoints.min.js'%}"></script>
			<script src="{% static 'myuser/js/util.js'%}"></script>
			<script src="{% static 'myuser/js/main.js'%}"></script>

	</body>
</html>

templates/myuser/login.html
{% extends 'myuser/base.html'%}
{% load static%}
{% block title%} Login {% endblock %}
{% block body%}
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
        {% if error_message %}
                    <p><strong>{{error_message}}</strong></p>
                {% endif  %}
					<form method="POST" action="">
					{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								{{form.password}}
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'myuser:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript" src="{% static 'myuser/js/login.js'%}"></script>
{% endblock%}

templates/myuser/registration_form.html
{% extends 'myuser/base.html'%}
{% load static%}
{% block title%} Register {% endblock %}
{% block body%}
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
                    {% if error_message %}
                    <p><strong>{{error_message}}</strong></p>
                {% endif  %}
					<form method="POST" action="">
					{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.user_type }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'myuser:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>	
    <script type="text/javascript" src="{% static 'myuser/js/register.js'%}"></script>
{% endblock%}

templates/myuser/search_ambulance.html
<!DOCTYPE html>
<html>
{% load static%}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial;
}

* {
  box-sizing: border-box;
}
header   {
  padding: 20px 30px;
}

#logo         {
  display: inline-block;
  color: #FFF;
  text-decoration: none;
  width: 49%;
}
nav     {
  width: 50%;
  display: inline-block;
  text-align: right;
  font-size:26px;
  font-family:"Courier New", Courier, monospace;
}
nav ul   {
  list-style: none;
  margin: 0;
}
nav ul li {
  display: inline-block;
}
nav ul li a    {
  color:#ed6a5a;
  text-decoration:none;
  display: inline-block;
  margin-bottom: 50px;
  padding: 10px 15px;
  border-radius: 3px;
  transition: 0.3s ease all;
}
nav ul li a:hover   {
  background:#7abecc;
  color:#fff;
}

form.example input[type=text] {
  padding: 10px;
  font-size: 17px;
  border: 1px solid grey;
  float: left;
  width: 80%;
  background: #f1f1f1;
}

form.example button {
  float: left;
  width: 20%;
  padding: 10px;
  background: #2196F3;
  color: white;
  font-size: 17px;
  border: 1px solid grey;
  border-left: none;
  cursor: pointer;
}

form.example button:hover {
  background: #0b7dda;
}

form.example::after {
  content: "";
  clear: both;
  display: table;
}
</style>
</head>
<body>
    <header>

        <a id="logo" href="#">
<img src="{% static 'myuser/images/logo.png'%}" alt="Logo">        </a>
        <nav>
            <ul>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </nav>

    </header>
<p style="text-align: center;color:#ed6a5a;">Enter Pincode to search</p>
<form class="example" action="#" method="POST" style="margin:auto;max-width:500px">
{% csrf_token %}
  <input type="text" placeholder="Search.." name="pincode">
  <button type="submit"><i class="fa fa-search"></i></button>
</form>

</body>
</html> 